# Generated by Django 3.2.16 on 2023-05-18 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name for the task', max_length=128)),
                ('description', models.TextField(help_text='Describe this task')),
                ('schedule_time', models.DateTimeField(help_text='Time at which the task should execute')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current state of the task', max_length=32)),
                ('task_id_worker', models.CharField(blank=True, help_text='ID provider by the async worker process', max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who set this alert', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id_worker', models.CharField(help_text='ID provider by the async worker process', max_length=256)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('triggered', 'Triggered')], help_text='State of task', max_length=32)),
                ('failure_details', models.TextField(blank=True, help_text='Additional information regarding failure', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scheduled_task', models.ForeignKey(help_text='A reference to the Scheduled Task', on_delete=django.db.models.deletion.CASCADE, to='schedule_tasks.scheduledtask')),
            ],
        ),
    ]
